### ISSUE TITLE
Crash when parrying a guardian beam

### ISSUE THREAD

**Issue by LiamJTolentino** [Xires87/SwordParry#13]
While raiding an ocean monument, I attempted to parry the attacks from the guardian mobs. When I got a successful parry, the game froze for several seconds before crashing.
[crash-2024-12-03_22.27.07-server.txt](https://github.com/user-attachments/files/18002223/crash-2024-12-03_22.27.07-server.txt)
[latest.log](https://github.com/user-attachments/files/18002224/latest.log)

**Comment by Xires87** [comment]
The fix should soon be available on Curseforge and Modrinth.

One more thing, in case anyone experiences this after x.3.1 versions: `frycparry:counterattack` has to be in `avoids_guardian_thorns` tag, otherwise it will keep crashing due to guardian's thorns being parried and counterattack effect being reapplied infinitely.
