### ISSUE TITLE
feedback and sound

### ISSUE THREAD

**Issue by shinycolororange** [Xires87/SwordParry#9]
Hey there! First of all, I want to say that this mod is incredible. It brings a deep level of skill to Minecraft's combat, allowing, in theory, players who master the perfect parry to win against difficult mobs even without armor. You have my respect for creating such a simple but amazing mod.

After playing with it for a while, I noticed a few small things that could be improved, and I thought I'd share my thoughts here. With how tight the perfect parry window is, not having parry bound to right-click feels like too much of a disadvantage for the player. I am currently using an additional mod called "Keybind Fix" to enable parrying on right-click without losing the default right-click abilities. It might be helpful to recommend this mod in the description so players are aware of it.

Secondly, there is no difference in sound between a normal parry and a perfect parry. I think the player should be rewarded with a distinct and satisfying sound (as an audio cue) for executing a perfect parry, so they can better understand what's happening and feel more gratified.

And last is that having a perfect parry without any enchantment that reflects damage feels somewhat underwhelming in the early game for the difficulty to execute that. However, I don’t have a solution for this.

**Comment by Xires87** [comment]
Hello! Thanks for feedback. I'm glad you like my mod.

Regarding the keybinds, just unbind parry key and it will work with right click. There is no need to use additional mods (unless you play on 1.19 version, which is outdated and is missing a lot of improvements - I recommend switching to 1.20 or 1.21 if you do).

Custom sounds were suggested a few times. The problem is the sound itself. Finding a good, free sound is difficult.

If you feel, that performing perfect parry in early game is too difficult, you can, for example, increase parry ticks for early game items with a datapack (but, once again, it's something that is 1.20+ only).
